AWSTemplateFormatVersion: 2010-09-09
Description: EC2

Parameters:

  AMIId:
    Description: The ami to use (default Ubuntu 18.04 en la región us-east-1)
    Type: AWS::EC2::Image::Id
    Default: ami-013f17f36f8b1fefb

  DBPassword:
    Description: Database password
    Type: String
    NoEcho: true
    MinLength: 8

  S3BucketName:
    Description: Name of the bucket
    Type: String
    Default: sanguino.cloudapps.urjc

  JarDownloadUrl:
    Description: URL to download and rumthe .jar file
    Type: String
    Default: https://s3.amazonaws.com/practica-2.cloud.michel/app.jar

Resources:

  S3WritableRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
      Path: /

  S3RolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: s3WritablePolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action: 's3:*'
          Resource: [!Sub 'arn:aws:s3:::${S3BucketName}/*']
      Roles:
      - !Ref S3WritableRole

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
      - !Ref S3WritableRole

  S3Bucket:
    Type: AWS::S3::Bucket
    DependsOn: S3WritableRole
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref S3BucketName
      AccessControl: PublicRead

  Ec2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    DependsOn: S3Bucket
    Properties:
      GroupDescription: Allow 8843 from my host
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 8443
        ToPort: 8443
        CidrIp: 90.74.96.228/32

  RdsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    DependsOn: Ec2SecurityGroup
    Properties:
      GroupDescription: SG for MySQL RDS
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        SourceSecurityGroupName: !Ref Ec2SecurityGroup

  RdsDBInstance:
    Type: AWS::RDS::DBInstance
    DependsOn: RdsSecurityGroup
    Properties:
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 8
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: false
      DBInstanceIdentifier: rdsp2
      DBName: rdsp2
      Engine: mysql
      EngineVersion: 8.0
      MasterUsername: rdsp2
      MasterUserPassword: !Ref DBPassword
      MultiAZ: false
      PubliclyAccessible: false
      StorageEncrypted: false
      VPCSecurityGroups:
      - !GetAtt RdsSecurityGroup.GroupId

  EC2Instance:
    Type: AWS::EC2::Instance
    DependsOn: RdsDBInstance
    Properties:
      ImageId: !Ref AMIId
      InstanceType: t2.micro
      IamInstanceProfile: !Ref InstanceProfile
      SecurityGroupIds:
      - !Ref Ec2SecurityGroup
      UserData:
        Fn::Base64:
          Fn::Sub:
          - |
            #!/bin/bash -xe
            sudo apt update && sudo apt install -y openjdk-11-jre
            export BUCKET_NAME=${S3BucketName}
            export RDS_ENDPOINT=${RdsDBInstanceAddress}
            export REGION=us-east-1
            export RDS_DATABASE=rdsp2
            export RDS_PASS=${DBPassword}
            export RDS_USER=rdsp2
            wget -O app.jar ${JarDownloadUrl}
            java -jar -Dspring.profiles.active=production app.jar
          - S3BucketName: !Ref S3BucketName
            RdsDBInstanceAddress: !GetAtt RdsDBInstance.Endpoint.Address
            DBPassword: !Ref DBPassword
            JarDownloadUrl: !Ref JarDownloadUrl

Outputs:
  PublicDns:
    Value: !GetAtt EC2Instance.PublicDnsName
    Description: "P2 - PublicDns"
  EventsEndpoint:
    Value:
      !Join
    - ''
    - - "https://"
      - !GetAtt EC2Instance.PublicDnsName
      - ":8443"
      - "/api/events/"
    Description: "P2 - EventsEndpoint to test connections"